name: Build & Publish Debug APK

on:
 push:
  branches:
   - build-debug-ci

jobs:
  apk:
    name: Release APK
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        working-directory: ./EasySO
        run: chmod +x ./gradlew
        
      - name: Generate Debug APK
        working-directory: ./EasySO
        run: ./gradlew clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: EasySO/app/build/outputs/apk/debug/app-debug.apk

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(date +'%Y-%m-%d')

      - name: Bump version and push tag
        id: semantic_version
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
        
      - name: Releasing using Hub
        uses: wanakubwa/action-release-apk@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN  }}
          APP_FOLDER: EasySO/app
          RELEASE_TITLE: Release-Debug-${{ steps.semantic_version.outputs.new_version }}
