name: Build & Publish Debug APK

on:
 push:
  branches:
   - main

jobs:
  apk:
    name: Release APK
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        working-directory: ./EasySO
        run: chmod +x ./gradlew
        
      - name: Generate Debug APK
        working-directory: ./EasySO
        run: ./gradlew clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: EasySO/app/build/outputs/apk/debug/app-debug.apk

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: Create Release and Upload debug APK
        uses: ShaunLWM/action-release-debugapk@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN  }}
          APP_FOLDER: EasySO/app
          RELEASE_TITLE: Release ${{ steps.get_version.outputs.VERSION }}
